language: ruby

rvm:
  - 2.1.0

before_script:
  - cd ngapp
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - cd ..

script:
  - bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake