language: ruby
rvm:
- 2.1.1
before_install:
- cd ngapp
- npm install -g bower grunt-cli
- npm install
- bower install
- cd ..
before_script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake ngbuild
script:
- bundle exec rake travis
deploy:
  provider: heroku
  api_key:
    secure: mA2vPAcUGKPEDi5q5tGvhKVrCA5z8q+46JwiR6NuthIX0pR6mySiMiUocx75cDlVzRTijX1cT5CULBAbln9GZYiS1My1jbRj+Cg1UdhN81RTI5z78o4AMLQSRLp1CFEuHzbkRJ/FTKADXif8ET+NB9AL1OETOoZ2QQDAcQURDnc=
  app: shelfofbooks
  on:
    repo: Absor/bookshelf
  run: rake db:migrate
  strategy: git